require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomVideosController do

  # This should return the minimal set of attributes required to create a valid
  # CustomVideo. As you add validations to CustomVideo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "path" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomVideosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all custom_videos as @custom_videos" do
      custom_video = CustomVideo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:custom_videos).should eq([custom_video])
    end
  end

  describe "GET show" do
    it "assigns the requested custom_video as @custom_video" do
      custom_video = CustomVideo.create! valid_attributes
      get :show, {:id => custom_video.to_param}, valid_session
      assigns(:custom_video).should eq(custom_video)
    end
  end

  describe "GET new" do
    it "assigns a new custom_video as @custom_video" do
      get :new, {}, valid_session
      assigns(:custom_video).should be_a_new(CustomVideo)
    end
  end

  describe "GET edit" do
    it "assigns the requested custom_video as @custom_video" do
      custom_video = CustomVideo.create! valid_attributes
      get :edit, {:id => custom_video.to_param}, valid_session
      assigns(:custom_video).should eq(custom_video)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomVideo" do
        expect {
          post :create, {:custom_video => valid_attributes}, valid_session
        }.to change(CustomVideo, :count).by(1)
      end

      it "assigns a newly created custom_video as @custom_video" do
        post :create, {:custom_video => valid_attributes}, valid_session
        assigns(:custom_video).should be_a(CustomVideo)
        assigns(:custom_video).should be_persisted
      end

      it "redirects to the created custom_video" do
        post :create, {:custom_video => valid_attributes}, valid_session
        response.should redirect_to(CustomVideo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved custom_video as @custom_video" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomVideo.any_instance.stub(:save).and_return(false)
        post :create, {:custom_video => { "path" => "invalid value" }}, valid_session
        assigns(:custom_video).should be_a_new(CustomVideo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomVideo.any_instance.stub(:save).and_return(false)
        post :create, {:custom_video => { "path" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested custom_video" do
        custom_video = CustomVideo.create! valid_attributes
        # Assuming there are no other custom_videos in the database, this
        # specifies that the CustomVideo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomVideo.any_instance.should_receive(:update).with({ "path" => "MyString" })
        put :update, {:id => custom_video.to_param, :custom_video => { "path" => "MyString" }}, valid_session
      end

      it "assigns the requested custom_video as @custom_video" do
        custom_video = CustomVideo.create! valid_attributes
        put :update, {:id => custom_video.to_param, :custom_video => valid_attributes}, valid_session
        assigns(:custom_video).should eq(custom_video)
      end

      it "redirects to the custom_video" do
        custom_video = CustomVideo.create! valid_attributes
        put :update, {:id => custom_video.to_param, :custom_video => valid_attributes}, valid_session
        response.should redirect_to(custom_video)
      end
    end

    describe "with invalid params" do
      it "assigns the custom_video as @custom_video" do
        custom_video = CustomVideo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomVideo.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom_video.to_param, :custom_video => { "path" => "invalid value" }}, valid_session
        assigns(:custom_video).should eq(custom_video)
      end

      it "re-renders the 'edit' template" do
        custom_video = CustomVideo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomVideo.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom_video.to_param, :custom_video => { "path" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested custom_video" do
      custom_video = CustomVideo.create! valid_attributes
      expect {
        delete :destroy, {:id => custom_video.to_param}, valid_session
      }.to change(CustomVideo, :count).by(-1)
    end

    it "redirects to the custom_videos list" do
      custom_video = CustomVideo.create! valid_attributes
      delete :destroy, {:id => custom_video.to_param}, valid_session
      response.should redirect_to(custom_videos_url)
    end
  end

end
